name: CI

on:
  push:
    branches:
      - main
      - structureDev
      - solutions
      - dev
      - updated-ci
  pull_request:
    branches:
      - main
      - structureDev
      - solutions
      - dev
      - updated-ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libgtest-dev build-essential clang-format ninja-build

      - name: Build and install Google Test
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp ./lib/*.a /usr/lib

      - name: Configure the project
        run: cmake -S . -B build

      - name: Build Core Tests (test_builder & test_runner)
        run: |
          cmake --build build --target test_test_builder
          cmake --build build --target test_test_runner

      - name: Run Core Tests (test_builder & test_runner)
        run: |
          cd build
          ctest -R test_test_builder --output-on-failure
          ctest -R test_test_runner --output-on-failure

      - name: Build the entire project
        run: cmake --build build
