name: CI

on:
  push:
    branches:
      - main
      - structureDev
  pull_request:
    branches:
      - main
      - structureDev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libgtest-dev build-essential clang-format

    - name: Build and install Google Test
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp ./lib/*.a /usr/lib

    - name: Check code formatting
      run: |
        clang-format --version
        find . -name '*.cpp' -o -name '*.hpp' | xargs clang-format --dry-run --Werror

    - name: Configure the project
      run: cmake -S . -B build

    - name: Build the project
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

